config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root "home#index"

  namespace :buzzer do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    get 'jobs', to: 'home#jobs', as: 'jobs'
    get 'job/:id', to: 'home#job_show', as: 'job_show'
    resources :accounts
    resources :activities
    resources :transactions
    resources :credits
    resources :buzzer_shares
  end

  namespace :business do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :billings
    resources :accounts
    resources :promotions
    resources :vouchers
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end
end

app/views/shareds/layout/_nav.html.haml
%nav
  .nav-wrapper
    %a.brand-logo{:href => "#{root_url}"}
      %i.material-icons.dp48 person_pin
      SocialBuzzer
    %ul.right.hide-on-med-and-down
      - if current_user.present?
        %li
          %a{:href => "badges.html"}
            Forum
            %i.material-icons.right question_answer
        %li
          %a{:href => "badges.html"}
            Get Jobs
            %i.material-icons.right assignment
        %li
          %a{:href => "badges.html"}
            Get Coupons
            %i.material-icons.right redeem
      - else
        %li
          %a{:href => "#{new_user_registration_url}"}
            SignUp
            %i.material-icons.right assignment
        %li
          %a{:href => "#{new_user_session_url}"}
            Login
            %i.material-icons.right vpn_key
      %li
        %a{:href => "sass.html"}
          %i.material-icons search
      - if current_user.present?
        %li
          %a.button-collapse-nav{"data-activates" => "slide-out", :href => "#"}
            %i.material-icons more_vert

app/views/shareds/layout/_side_nav.html.haml
- if current_user.present?
  %ul#slide-out.side-nav
    %li
      .userView
        .background
        %a{:href => "#!user"}
          %img.circle{:src => "#{current_user.avatar.url}"}
        %a{:href => "#!name"}
          %span.white-text.name #{current_user.username}
        %a{:href => "#!email"}
          %span.white-text.email #{current_user.email}
    %li
      %a{:href => "#!"}
        %i.material-icons> cloud
        First Link With Icon
    %li
      %a{:href => "#!"} Second Link
    %li
      .divider
    %li
      %a.subheader Subheader

    - if current_user.is_buzzer?
      %li
        = link_to 'Edit Profile', edit_buzzer_account_path(current_user)
    - elsif current_user.is_business?
      %li
        = link_to 'Edit Profile', edit_business_account_path(current_user)
    %li
      = link_to 'SignOut'.html_safe, destroy_user_session_path, method: 'delete', class: 'waves-effect'