config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root "home#index"

  namespace :buzzer do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    get 'jobs', to: 'home#jobs', as: 'jobs'
    get 'job/:id', to: 'home#job_show', as: 'job_show'
    resources :accounts
    resources :activities
    resources :transactions
    resources :credits
    resources :buzzer_shares
  end

  namespace :business do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :billings
    resources :accounts
    resources :promotions
    resources :vouchers
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end
end

app/views/layouts/dashboard/_footer.html.haml
%footer.footer
  %span.pull-right
    Example text
  Company 2015-2020

app/views/layouts/dashboard/_header.html.haml
#header
  #logo.light-version
    %span
      SOCIALFEEDS.COM
  %nav{:role => "navigation"}
    .header-link.hide-menu
      %i.fa.fa-bars
    .small-logo
      %span.text-primary SOCIALFEEDS.COM
    %form.navbar-form-custom{:action => "#", :method => "post", :role => "search"}
      .form-group
        %input.form-control{:name => "search", :placeholder => "Search something special", :type => "text"}
    .mobile-menu
      %button.navbar-toggle.mobile-menu-toggle{"data-target" => "#mobile-collapse", "data-toggle" => "collapse", :type => "button"}
        %i.fa.fa-chevron-down
      #mobile-collapse.collapse.mobile-navbar
        %ul.nav.navbar-nav
          %li
            %a{:href => "login.html"} Login
          %li
            %a{:href => "login.html"} Logout
          %li
            %a{:href => "profile.html"} Profile

    .navbar-right
      %ul.nav.navbar-nav.no-borders
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.pe-7s-speaker
          %ul.dropdown-menu.hdropdown.notification.animated.flipInX
            - (0..4).each do |f|
              %li
                %a
                  %span.label.label-success NEW
                  It is a long established.
            %li.summary
              = link_to 'See all notifications', '#'

        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.pe-7s-keypad
          .dropdown-menu.hdropdown.bigmenu.animated.flipInX
            %table
              %tbody
                %tr
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-portfolio.text-info
                      %h5 Campaigns
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-graph1.text-danger
                      %h5 Analytics
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-global.text-success
                      %h5 Blogs
                %tr
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-box1.text-success
                      %h5 Vouchers
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-cart.text-danger
                      %h5 Penjualan
                  %td
                    = link_to '#' do
                      %i.pe.pe-7s-comment.text-info
                      %h5 Forum
                      
        %li.dropdown
          %a.dropdown-toggle.label-menu-corner{"data-toggle" => "dropdown", :href => "#"}
            %i.pe-7s-mail
            %span.label.label-success 4
          %ul.dropdown-menu.hdropdown.animated.flipInX
            .title
              You have 4 new messages
            - (0..4).each do |f|
              %li
                = link_to 'It is a long established.' ,'#'
            %li.summary
              = link_to 'See All Messages', '#'
        %li
          %a#sidebar.right-sidebar-toggle{:href => "#"}
            %i.pe-7s-upload.pe-7s-news-paper
        %li.dropdown
          = link_to destroy_user_session_path, method: 'delete' do
            %i.pe-7s-upload.pe-rotate-90

app/views/layouts/dashboard/_right_sidebar.html.haml
#right-sidebar.animated.fadeInRight
  .p-m
    %button#sidebar-close.right-sidebar-toggle.sidebar-button.btn.btn-default.m-b-md
      %i.pe.pe-7s-close
    %div
      %span.font-bold.no-margins Analytics
      %br
      %small Lorem Ipsum is simply dummy text of the printing simply all dummy text.
    .row.m-t-sm.m-b-sm
      .col-lg-6
        %h3.no-margins.font-extra-bold.text-success 300,102
        .font-bold
          98%
          %i.fa.fa-level-up.text-success
      .col-lg-6
        %h3.no-margins.font-extra-bold.text-success 280,200
        .font-bold
          98%
          %i.fa.fa-level-up.text-success
    .progress.m-t-xs.full.progress-small
      .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "25", :role => "progressbar", :style => "width: 25%"}
        %span.sr-only 35% Complete (success)
  .p-m.bg-light.border-bottom.border-top
    %span.font-bold.no-margins Social talks
    %br
    %small Lorem Ipsum is simply dummy text of the printing simply all dummy text.
    .m-t-md
      .social-talk
        .media.social-profile.clearfix
          %a.pull-left
            %img{:alt => "profile-picture", :src => "images/a1.jpg"}/
          .media-body
            %span.font-bold John Novak
            %small.text-muted 21.03.2015
            .social-content.small
              Injected humour, or randomised words which don't look even slightly believable.
      .social-talk
        .media.social-profile.clearfix
          %a.pull-left
            %img{:alt => "profile-picture", :src => "images/a3.jpg"}/
          .media-body
            %span.font-bold Mark Smith
            %small.text-muted 14.04.2015
            .social-content
              Many desktop publishing packages and web page editors.
      .social-talk
        .media.social-profile.clearfix
          %a.pull-left
            %img{:alt => "profile-picture", :src => "images/a4.jpg"}/
          .media-body
            %span.font-bold Marica Morgan
            %small.text-muted 21.03.2015
            .social-content
              There are many variations of passages of Lorem Ipsum available, but the majority have
  .p-m
    %span.font-bold.no-margins Sales in last week
    .m-t-xs
      .row
        .col-xs-6
          %small Today
          %h4.m-t-xs
            $170,20
            %i.fa.fa-level-up.text-success
        .col-xs-6
          %small Last week
          %h4.m-t-xs
            $580,90
            %i.fa.fa-level-up.text-success
      .row
        .col-xs-6
          %small Today
          %h4.m-t-xs
            $620,20
            %i.fa.fa-level-up.text-success
        .col-xs-6
          %small Last week
          %h4.m-t-xs
            $140,70
            %i.fa.fa-level-up.text-success
    %small
      Lorem Ipsum is simply dummy text of the printing simply all dummy text.
      Many desktop publishing packages and web page editors.

app/views/layouts/dashboard/_side_menu.html.haml
%aside#menu
  #navigation
    .profile-picture
      = link_to dashboard(current_user) do
        .img-circle.thumb.m-auto.mb-20
          = image_tag current_user.avatar.url(:thumb)
      .stats-label.text-color
        %span.font-extra-bold.font-uppercase Alam Topani H
        .dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %small.text-muted
              Pengaturan
              %b.caret
          %ul.dropdown-menu.animated.flipInX.m-t-xs
            %li
              = link_to 'Beranda', dashboard(current_user)
            %li
              = link_to 'Pengaturan Profil', edit_account(current_user)
            %li.divider
            %li
              = link_to 'Keluar', destroy_user_session_path, method: 'delete'

        #sparkline1.small-chart.m-t-sm
        %div
          = link_to buzzer_transactions_path do
            %h4.font-extra-bold.m-b-xs.side-money
              IDR. <span id='money'>#{get_nominal(current_user.money)}</span>
            %small.text-muted SALDO

    %ul#side-menu.nav
      %li{class: active_sidebar?(:home, :dashboard)}
        = link_to 'Beranda', dashboard(current_user)

      - if current_user.is_business?
        %li{class: active_sidebar?(:billings, :all)}
          = link_to business_billings_path do
            %span.nav-label Billings
        %li{class: active_sidebar?(:promotions, :show)}
          %a{:href => "#"}
            %span.nav-label Analytics
            %span.fa.arrow
          %ul.nav.nav-second-level
            - @get_analytics.each do |f|
              %li
                = link_to f.title, business_promotion_path(f)
        %li{class: active_sidebar?(:promotions, :new) || active_sidebar?(:promotions, :index) || active_sidebar?(:promotions, :edit)}
          %a{:href => "#"}
            %span.nav-label Promotions
            %span.fa.arrow
          %ul.nav.nav-second-level
            %li{class: active_sidebar?(:promotions, :new) || active_sidebar?(:promotions, :edit)}
              = link_to 'Buat Promotion', new_business_promotion_path
            %li{class: active_sidebar?(:promotions, :index)}
              = link_to 'List Promotions', business_promotions_path
        / %li
        /   %a{:href => "#"}
        /     %span.nav-label Vouchers
        /     %span.fa.arrow
        /   %ul.nav.nav-second-level
        /     %li
        /       = link_to 'Buat Voucher', '#'
        /     %li
        /       = link_to 'List Vouchers', '#'
        /     %li
        /       = link_to 'Penjualan Vouchers', '#'
        / %li
        /   = link_to '#' do
        /     %span.nav-label Forums
        /     %span.label.label-info.pull-right NEW

      - elsif current_user.is_buzzer?
        %li{class: active_sidebar?(:activities, :all)}
          = link_to 'Aktivitas Saya', buzzer_activities_path
        %li{class: active_sidebar?(:credits, :all)}
          = link_to 'Pendapatan', buzzer_credits_path
        %li{class: active_sidebar?(:home, :jobs)}
          = link_to 'Mulai Bekerja', buzzer_jobs_path