config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root "home#index"

  namespace :buzzer do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    get 'jobs', to: 'home#jobs', as: 'jobs'
    get 'job/:id', to: 'home#job_show', as: 'job_show'
    resources :accounts
    resources :activities
    resources :transactions
    resources :credits
    resources :buzzer_shares
  end

  namespace :business do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :billings
    resources :accounts
    resources :promotions
    resources :vouchers
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end
end

app/models/buzzer.rb
class Buzzer < User
  default_scope {where(type: 'Buzzer')}
  has_one :buzzer_profile, foreign_key: 'buzzer_id'
  accepts_nested_attributes_for :buzzer_profile, allow_destroy: true
  
  after_initialize :prepare_profile

  # ------- RELATIONSHIP --------
  def buzzer_shares
    buzzer_shares = BuzzerShare.where(buzzer_id: self.id)
    return buzzer_shares
  end

  # ------- ATTRIBUTES --------
  def fullname
    self.buzzer_profile.first_name + ' ' + self.buzzer_profile.last_name if self.buzzer_profile.first_name?
  end

  def get_industries
    self.buzzer_profile.industries.reject(&:empty?).join(', ') if self.buzzer_profile.present?
  end

  def get_progress_profile_buzzer
    progress = 17

    progress = progress + 7 if self.avatar.present?
    progress = progress + 7 if self.phone.present?

    progress = progress + 6 if self.twitter_uid.present?
    progress = progress + 6 if self.facebook_uid.present?
    progress = progress + 6 if self.instagram_uid.present?
    progress = progress + 5 if self.google_uid.present?
    progress = progress + 5 if self.youtube_uid.present?

    if self.buzzer_profile.present?
      progress = progress + 5 if self.buzzer_profile.first_name.present?
      progress = progress + 5 if self.buzzer_profile.last_name.present?
      progress = progress + 5 if self.buzzer_profile.born.present?
      progress = progress + 5 if self.buzzer_profile.gender.present?
      progress = progress + 5 if self.buzzer_profile.work.present?
      progress = progress + 5 if self.buzzer_profile.from.present?
      progress = progress + 5 if self.buzzer_profile.industries.present?
    end

    if self.address.present?
      progress = progress + 5 if self.address.province.present?
      progress = progress + 5 if self.address.city.present?
      progress = progress + 5 if self.address.address.present?
      progress = progress + 3.5 if self.address.longitude.present?
      progress = progress + 3.5 if self.address.latitude.present?
    end

    return progress
  end

  private
    def prepare_profile
      self.buzzer_profile = BuzzerProfile.new if self.buzzer_profile.blank?
    end
end

app/controllers/business/accounts_controller.rb
class Business::AccountsController < Business::BusinessApplicationController
  include PathHelper
  prepend_before_filter :draw_password, only: :update
  
  def edit
    @account = Business.find current_user
  end

  def update
    @account = Business.find current_user
    if @account.update(params_permit)
      redirect_to edit_account(current_user), notice: 'Successfully updated!'
    else
      redirect_to edit_account(current_user), alert: @account.errors.full_messages.join('<br/>')
    end
  end

  private
    def params_permit
      params.require(:business).permit(:id, :username, :email, :phone, :pin, :avatar, :password, :password_confirmation,
                                      business_info_attributes: [:name, :website, :admin_name, :phone_admin, :about, :from, :agreement, industries: []],
                                      address_attributes: [:country, :province, :city, :address, :longitude, :latitude]
                                    )
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:business].delete(attr)
      end if params[:business] && params[:business][:password].blank?
    end
end

app/controllers/buzzer/accounts_controller.rb
class Buzzer::AccountsController < Buzzer::BuzzerApplicationController
  include PathHelper
  prepend_before_filter :draw_password, only: :update
  
  def edit
    @account = Buzzer.find current_user
  end

  def update
    @account = Buzzer.find current_user
    if @account.update(params_permit)
      redirect_to edit_account(current_user), notice: 'Successfully updated!'
    else
      redirect_to edit_account(current_user), alert: @account.errors.full_messages.join('<br/>')
    end
  end

  private
    def params_permit
      params.require(:buzzer).permit(:username, :email, :phone, :pin, :avatar, :password, :password_confirmation,
                                      buzzer_profile_attributes: [:first_name, :last_name,:born, :gender, :from, :agreement, :work, industries: []],
                                      address_attributes: [:country, :province, :city, :address, :longitude, :latitude]
                                    )
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:buzzer].delete(attr)
      end if params[:buzzer] && params[:buzzer][:password].blank?
    end
end

app/controllers/buzzer/activities_controller.rb
class Buzzer::ActivitiesController < Buzzer::BuzzerApplicationController
  def index
    @activity_snapshots = current_user.activity_snapshots.order("id desc").page(params[:page]).per(10)
  end
end

app/controllers/buzzer/buzzer_application_controller.rb
class Buzzer::BuzzerApplicationController < ApplicationController
  layout 'dashboard'
end

app/controllers/buzzer/buzzer_shares_controller.rb
class Buzzer::BuzzerSharesController < Buzzer::BuzzerApplicationController
  include ActionView::Helpers::NumberHelper
  include CurrencyHelper

  # POST STATUS WITH POPUP
  def create
    unless check_available(params[:promotion_id], params[:provider]).present?
      if check_quota(params[:promotion_id]).present?
        if params[:provider] == 'twitter'
          @buzzer_share = post_tweet(params[:tweet]) 
          post_link = params[:tweet][:twit_url]
        elsif params[:provider] == 'facebook'
          post_link = params[:link]
        end

        @buzzer_share = BuzzerShare.create(
          post_link: post_link,
          buzzer_id: current_user.id,
          promotion_id: params[:promotion_id],
          post_id: params[:provider] == 'twitter' ? @tweet_obj.id : params[:post_id],
          provider: params[:provider]
        )
        
        if @buzzer_share.present?
          save_activity(@buzzer_share)
          render json: {
            success: true,
            message: "Berhasil, promosi/iklan ini sudah anda share di #{params[:provider]} anda!"
          }
        end
      else
        render json: {
          success:false,
          message: "Gagal, kuota buzzer untuk promosi/iklan ini sudah melewati batas yang telah ditentukan, silahkan pilih yang lain!"
        }
      end
    else
      render json: {
        success:false,
        message: "Gagal, anda sudah pernah share promosi/iklan ini menggunakan #{params[:provider]}!"
      }
    end
  end

  private
    def save_activity(share)
      # Update Promotion
      promotion = share.promotion
      promotion.quota_share = promotion.quota?
      promotion.save

      # Update Status Share
      share.update(status: BuzzerShare::SUCCESS)

      # Add Activity
      activity = ActivitySnapshot.create(
        title: "Telah berhasil, share promosi/iklan (<b>#{share.promotion.title}</b>) via <b>#{share.provider}</b> dengan reward <b>Rp.#{share.reward}</b>", 
        activitiable_type: "#{share.class.name}", activitiable_id: "#{share.id}", user_id: current_user.id
      )

      # Update User Money
      current_user.update(money: current_user.money + share.reward)

      # Add Transaction Snapshot
      transaction_snapshot = TransactionSnapshot.create(
        title: "Saldo Masuk, reward untuk share promosi/iklan!",
        description: "Berhasil, share promosi/iklan (<b>#{share.promotion.title}</b>) via <b>#{share.provider}</b> post id <b>#{share.post_id}</b> dengan reward <b>Rp.#{share.reward}</b>, maka pendapatan anda bertambah menjadi <b>Rp.#{get_nominal(current_user.money)}</b>", 
        transactionable_type: "#{share.class.name}", transactionable_id: "#{share.id}", user_id: current_user.id,
        credit: share.reward, balance: current_user.money, activity_snapshot_id: activity.id
      )
    end

    def post_tweet(added_data)
      client = Twitter::REST::Client.new do |c|
        c.consumer_key        = Rails.application.secrets.consumer_key
        c.consumer_secret     = Rails.application.secrets.consumer_secret
        c.access_token        = current_user.twitter_token
        c.access_token_secret = current_user.twitter_secret
      end

      tweet = added_data[:twit_message] + ' ' + added_data[:twit_url]
      @tweet_obj = client.update(tweet)
    end

    def check_available(promotion_id, provider)
      promotion = BuzzerShare.where(buzzer_id: current_user.id).where(promotion_id: promotion_id).where(provider: provider)
    end

    def check_quota(promotion_id)
      promotion = Promotion.find_by(id: promotion_id)
      promotion.status != Promotion::INACTIVE && promotion.check_quota?
    end
end

app/controllers/buzzer/credits_controller.rb
class Buzzer::CreditsController < Buzzer::BuzzerApplicationController
  def index
    @buzzer_shares = BuzzerShare.where(buzzer_id: current_user.id).order("id desc").page(params[:page]).per(10)
  end
end

app/controllers/buzzer/home_controller.rb
class Buzzer::HomeController < Buzzer::BuzzerApplicationController
  def dashboard
    @activities = ActivitySnapshot.statuses.order("id desc").page(params[:page]).per(10)
  end

  def jobs
    @promotions = Promotion.all_active.order("id desc").page(params[:page]).per(10)
  end

  def job_show
    @promotion = Promotion.all_active.find_by(id: params[:id])
    
    # count visit
    if @promotion.visitor_snapshot.present?
      @visit = @promotion.visitor_snapshot
      impressionist(@visit)
    end
  end
end

app/controllers/buzzer/transactions_controller.rb
class Buzzer::TransactionsController < Buzzer::BuzzerApplicationController
  def index
    @transactions = TransactionSnapshot.where(user_id: current_user.id).order("id desc").page(params[:page]).per(10)
  end
end

app/views/buzzer/accounts/_social_account.html.haml
%label Verifikasi akun facebook?
.hpanel.hgfb.contact-panel.connect-social-account
  .panel-body
    .row.valign-wrapper
      .col-xs-2
        = link_to "https://facebook.com/#{current_user.facebook_uid}" do
          %img.img-circle{src: current_user.facebook_avatar.url(:thumb)}
      .col-xs-7
        %span
          - unless current_user.facebook_uid.present?
            %br Silahkan verifikasi akun facebook anda terlebih dahulu
          - else
            %small 
              Your twitter account has been successfully connected <br>at <b>#{current_user.facebook_oauth_token_register_at.strftime('%d %B %Y - %H:%M:%S')}</b> <br>by uid <b>#{current_user.facebook_uid}</b> and you have <b>#{current_user.facebook_friends_count}</b> friends
  
      .col-xs-3
        = link_to user_facebook_omniauth_authorize_path, class: 'btn btn-full btn-fb' do
          - unless current_user.facebook_uid.present?
            %i.fa.fa-facebook{"aria-hidden" => "true"} 
            %br
            Verifikasi
          - else
            %i.fa.fa-facebook{"aria-hidden" => "true"}
            %br
            %i.fa.fa-check-circle-o
            Terkoneksi

%label Verifikasi akun twitter?
.hpanel.hgtw.contact-panel.connect-social-account
  .panel-body
    .row.valign-wrapper
      .col-xs-2
        = link_to "https://twitter.com/#{current_user.twitter_uid}" do
          %img.img-circle{src: current_user.twitter_avatar.url(:thumb)}
      .col-xs-7
        %span
          - unless current_user.twitter_uid.present?
            %br Silahkan verifikasi akun twitter anda terlebih dahulu
          - else
            %small 
              Your twitter account has been successfully connected <br>at <b>#{current_user.twitter_oauth_token_register_at.strftime('%d %B %Y - %H:%M:%S')}</b> <br>by uid <b>#{current_user.twitter_uid}</b> and you have <b>#{current_user.twitter_followers_count}</b> followers
      .col-xs-3
        = link_to user_twitter_omniauth_authorize_path, class: 'btn btn-full btn-tw' do
          - unless current_user.twitter_uid.present?
            %i.fa.fa-twitter{"aria-hidden" => "true"}
            %br
            Verifikasi
          - else
            %i.fa.fa-twitter{"aria-hidden" => "true"}
            %br
            %i.fa.fa-check-circle-o
            Terkoneksi
.text-right.m-t-xs

app/views/buzzer/accounts/edit.html.haml
.row
  .col-lg-4
    .hpanel.hgreen
      .panel-body
        .pull-right.text-right
          .btn-group
            - if current_user.facebook_uid.present?
              = link_to "http://facebook.com/#{current_user.facebook_uid}", class: 'btn btn-default btn-xs' do
                %i.fa.fa-facebook
            - if current_user.twitter_uid.present?
              = link_to "http://twitter.com/#{current_user.twitter_uid}", class: 'btn btn-default btn-xs' do
                %i.fa.fa-twitter
        = image_tag current_user.avatar.url(:thumb), class: 'img-circle m-b m-t-md thumb'
        %h3
          = @account.username
        .text-muted.font-bold.m-b-xs 
          = @account.email
        %small
          = @account.try(:address).try(:place_info)
        %br
        %br
        .progress.m-t-xs.full.progress
          .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{@account.get_progress_profile_buzzer}", :role => "progressbar", :style => "width: #{@account.get_progress_profile_buzzer}%"}
            %small #{@account.get_progress_profile_buzzer}% Complete Profile
      / .border-right.border-left
      /   %section#map
      .panel-body
        %small Nama Lengkap
        %h4
          = @account.fullname
        %small Umur
        %h4
          #{@account.buzzer_profile.age} Tahun
        %small Jenis Kelamin
        %h4
          = @account.buzzer_profile.gender
        %small Pekerjaan
        %h4
          = @account.buzzer_profile.work
        %small Tertarik Industri
        %h4
          = @account.get_industries
        %small Alamat
        %h4
          = @account.address.sort_place_info
      .panel-footer.contact-footer
        .row
          .col-md-6.border-right
            .contact-stat
              %span Facebook Friends
              %strong #{current_user.facebook_friends_count}
          .col-md-6
            .contact-stat
              %span Twitter Followers
              %strong #{current_user.twitter_followers_count}
  .col-lg-8
    .hpanel
      .panel-body
        %h2{align: 'center'} Pengaturan
        %br
        #wizardControl.text-center.m-b-md
          %ul.nav.nav-tabs{role: "tablist"}
            %li.active{role: "presentation"}
              %a.btn.btn-default{"data-toggle" => "tab", "aria-controls" => "step1", role: "tab", :href => "#step1"} Pengaturan Akun
            %li{role: "presentation"}
              %a.btn.btn-default{"data-toggle" => "tab", "aria-controls" => "step2", role: "tab", :href => "#step2"} Pengaturan Profil
            %li{role: "presentation"}
              %a.btn.btn-default{"data-toggle" => "tab", "aria-controls" => "step3", role: "tab", :href => "#step3"} Pengaturan Alamat

        .tab-content
          #step1.p-m.tab-pane.active
            = form_for @account, url: buzzer_account_path(@account), method: 'put' do |f|
              .row
                .col-lg-12
                  .row
                    .form-group.col-lg-12
                      .card-content
                        %center
                          .avatar-edit-account
                            = image_tag current_user.avatar.url(:thumb)
                            = f.file_field :avatar
                      %br
                      %br
                    .form-group.col-lg-6
                      %em * 
                      = f.label :username
                      = f.text_field :username, required: true, class: 'form-control'
                    .form-group.col-lg-6
                      %em * 
                      = f.label :email
                      = f.email_field :email, required: true, class: 'form-control'
                    .form-group.col-lg-6
                      = f.label 'Kata sandi baru'
                      = f.password_field :password, class: 'form-control'
                    .form-group.col-lg-6
                      = f.label 'Konfirmasi kata sandi'
                      = f.password_field :password_confirmation, class: 'form-control'
                    .form-group.col-lg-12
                      %em * 
                      = f.label 'No.Handphone'
                      = f.text_field :phone, class: 'form-control', required: true

              .text-right.m-t-xs
                = submit_tag 'SIMPAN', class: 'btn btn-success'
              %hr
              = render 'buzzer/accounts/social_account'

          #step2.p-m.tab-pane
            = form_for @account, url: buzzer_account_path(@account), method: 'put' do |f|
              = f.fields_for :buzzer_profile do |p|
                = f.fields_for :address do |ad|
                  .row
                    .col-lg-12
                      .row
                        .form-group.col-lg-6
                          %em * 
                          = p.label 'Nama depan'
                          = p.text_field :first_name, required: true, class: 'form-control'
                        .form-group.col-lg-6
                          %em * 
                          = p.label 'Nama belakang'
                          = p.text_field :last_name, required: true, class: 'form-control'
                        .form-group.col-lg-6
                          %em * 
                          = p.label 'Tanggal Lahir'
                          = p.text_field :born, required: true, class: 'form-control datepicker', value: @account.buzzer_profile.present? && @account.buzzer_profile.born.present? ? format_date(@account.buzzer_profile.born) : format_date(Date.today - 17.years)
                        .form-group.col-lg-6
                          %em * 
                          = p.label 'Jenis kelamin'
                          = p.select :gender, get_gender, {prompt: 'Pilih Jenis Kelamin'}, required: true, class: 'form-control'
                        .form-group.col-lg-12
                          %em * 
                          = p.label 'Pekerjaan'
                          = p.text_field :work, required: true, class: 'form-control'
                        .form-group.col-lg-12
                          %em * 
                          = p.label 'Tertarik dengan industri'
                          = p.select :industries, get_industries, {prompt: 'Pilih Industri'}, required: true, multiple: true, class: 'form-control select2'
                        .form-group.col-lg-12
                          %em * 
                          = p.label 'Mengetahui situs ini dari'
                          = p.select :from, get_we_are_from, {prompt: 'Mengetahui situs ini dari'}, required: true, class: 'form-control'
                  %hr
                  .text-right.m-t-xs
                    = submit_tag 'SIMPAN', class: 'btn btn-success'

          #step3.p-m.tab-pane
            = form_for @account, url: buzzer_account_path(@account), method: 'put' do |f|
              = f.fields_for :address do |ad|
                .row
                  .col-lg-12
                    .row
                      .form-group.col-lg-6
                        %em * 
                        = ad.label 'Provinsi'
                        = ad.select :province, options_for_select(get_regions, ad.object.province), {prompt: 'Pilih Provinsi'}, 'data-node' => "buzzer", required: true, class: 'form-control select-province select2'
                      .form-group.col-lg-6
                        %em * 
                        = ad.label 'Kota'
                        .city-container
                          = ad.select :city, options_for_select(get_city(ad.object.province), ad.object.city), {prompt: 'Pilih Kota'}, required: true, class: 'form-control select2'
                      .form-group.col-lg-12
                        %em * 
                        = ad.label 'Alamat Lengkap'
                        = ad.text_field :address, required: true, class: 'form-control'
                      .form-group.col-lg-12
                        = ad.hidden_field :country, value: 'Indonesia'
                        = ad.hidden_field :latitude, class: 'latitude'
                        = ad.hidden_field :longitude, class: 'longitude'
                        %input#pac-input.controls{placeholder: "Tentukan Lokasi Persis Anda", type: "text"}
                        #map
                        #infowindow-content
                          %span#place-name.title
                          %br
                          Place ID
                          %span#place-id
                          %br
                          %span#place-address

                %hr
                .text-right.m-t-xs
                  = submit_tag 'SIMPAN', class: 'btn btn-success'

= render 'business/shareds/js_set_geo_map'