config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root "home#index"

  namespace :buzzer do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    get 'jobs', to: 'home#jobs', as: 'jobs'
    get 'job/:id', to: 'home#job_show', as: 'job_show'
    resources :accounts
    resources :activities
    resources :transactions
    resources :credits
    resources :buzzer_shares
  end

  namespace :business do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :billings
    resources :accounts
    resources :promotions
    resources :vouchers
  end

  resources :xhrs do
    collection do
      get :cities
    end
  end
end

app/models/promotion.rb
class Promotion
  include Mongoid::Document
  field :code, type: String
  field :title, type: String
  field :cover, type: String
  field :description, type: String
  field :content, type: String
  field :url, type: Array
  field :mention, type: Array
  field :hashtag, type: Array
  field :cities, type: Array
  field :range_age, type: String
  field :min_age, type: Integer
  field :max_age, type: Integer
  field :gender, type: String
  field :industries, type: Array
  field :providers, type: Array
  field :status, type: String, default: 'inactive'
  field :quota, type: Integer
  field :quota_share, type: Integer
  field :price, type: Integer
  field :fee, type: Integer
  field :total, type: Integer
  field :address, type: String
  field :longitude, type: String
  field :latitude, type: String
  field :url_facebook, type: String
  field :url_twitter, type: String
  field :url_instagram, type: String
  field :phone, type: String
  field :start_date, type: Date
  field :expired_date, type: Date
  field :created_at, type: DateTime
  field :updated_at, type: DateTime
  field :user_id, type: Integer

  mount_uploader :cover, CoverUploader

  scope :all_active, ->{where(status: { '$in': [self::HEADLINE, self::FEATURED, self::ACTIVE] }) }

  before_create :before_create_service
  before_save :before_update_service

  # ------- RELATIONSHIP --------
  def business
    business = Business.find_by(id: self.user_id)
    return business
  end

  def buzzer_shares
    buzzer_shares = BuzzerShare.where(promotion_id: self.id)
    return buzzer_shares
  end

  def visitor_snapshot
    visitor_snapshot = VisitorSnapshot.where(visitorable_type: self.class.name, visitorable_id: self.id.to_s).last || nil
    return visitor_snapshot
  end

  # ------- PACKAGE --------
  BASIC = 'basic'.freeze
  STANDAR = 'standar'.freeze
  PREMIUM = 'premium'.freeze
  PRESTIGE = 'prestige'.freeze

  # ------- STATUS --------
  HEADLINE = 'headline'.freeze
  FEATURED = 'featured'.freeze
  ACTIVE = 'active'.freeze
  INACTIVE = 'inactive'.freeze

  STATUSES = [self::INACTIVE, self::ACTIVE, self::HEADLINE, self::FEATURED].freeze
  DEFAULT_STATUSES = [self::ACTIVE, self::HEADLINE, self::FEATURED].freeze

  def status?
    case self.status
    when Promotion::HEADLINE then @klass = 'warning'
    when Promotion::FEATURED then @klass = 'success'
    when Promotion::ACTIVE   then @klass = 'info'
    when Promotion::INACTIVE then @klass = 'default'
    end

    return "<span class=\"label label-#{@klass}\">#{self.status.titleize}</span>".html_safe
  end

  def status_payment?
    if self.status == Promotion::INACTIVE
      return "<span class=\"label label-danger\">PENDING</span>".html_safe
    else
      return "<span class=\"label label-success\">SUDAH DIBAYAR</span>".html_safe
    end
  end

  # ------- ATTRIBUTES --------
  def get_address_lat
    self.latitude.present? ? self.latitude : -6.173664985778263
  end

  def get_address_long
    self.longitude.present? ? self.longitude : 106.82918787002563
  end

  def budget?
    budget = self.price.to_i - self.buzzer_shares.successed.sum(:reward)
  end

  def check_quota?
    self.buzzer_shares.successed.size.to_i < self.quota.to_i
  end

  def quota?
    count = self.quota.to_i - self.buzzer_shares.successed.size.to_i
  end

  def content_caption?
    message = self.hashtag.join(' ') + self.mention.join(' ')
  end

  def content_promo?
    message = self.hashtag.join(' ') + self.mention.join(' ') + self.content
  end

  def already_share(provider, current_user)
    self.buzzer_shares.where(provider: provider).where(buzzer_id: current_user.id).where(promotion_id: self.id)
  end

  def duration?
    if self.start_date.to_date == self.expired_date.to_date
      return self.start_date.strftime('%d %B %Y')
    elsif self.start_date.strftime('%B') == self.expired_date.strftime('%B')
      return "#{self.start_date.strftime('%d')} - #{self.expired_date.strftime('%d %b %Y')}"
    else
      return "#{self.start_date.strftime('%d %b')} - #{self.expired_date.strftime('%d %b %Y')}"
    end
  end

  def campaign_encript(current_user)
    campaign_encript = current_user.id.to_s + current_user.username + current_user.email + self.id
    return Digest::SHA1.hexdigest(campaign_encript)
  end

  def is_facebook_only?
    self.providers.include?('Facebook')
  end

  def is_twitter_only?
    self.providers.include?('Twitter')
  end

  private
    def before_create_service
      self.quota_share = self.quota
      self.code = 'P'+ 5.times.map{Random.rand(10)}.join
      self.created_at = Time.zone.now
      self.updated_at = Time.zone.now
    end

    def before_update_service
      self.updated_at = Time.zone.now
    end
end

app/controllers/business/accounts_controller.rb
class Business::AccountsController < Business::BusinessApplicationController
  include PathHelper
  prepend_before_filter :draw_password, only: :update
  
  def edit
    @account = Business.find current_user
  end

  def update
    @account = Business.find current_user
    if @account.update(params_permit)
      redirect_to edit_account(current_user), notice: 'Successfully updated!'
    else
      redirect_to edit_account(current_user), alert: @account.errors.full_messages.join('<br/>')
    end
  end

  private
    def params_permit
      params.require(:business).permit(:id, :username, :email, :phone, :pin, :avatar, :password, :password_confirmation,
                                      business_info_attributes: [:name, :website, :admin_name, :phone_admin, :about, :from, :agreement, industries: []],
                                      address_attributes: [:country, :province, :city, :address, :longitude, :latitude]
                                    )
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:business].delete(attr)
      end if params[:business] && params[:business][:password].blank?
    end
end

app/controllers/business/analytics_controller.rb
class Business::AnalyticsController < Business::BusinessApplicationController
  def index
    @analytics = ['Promotion 1', 'Promotion 1', 'Promotion 1']
  end

  def show
    @analytic = 'Promotion 1'
  end
end

app/controllers/business/billings_controller.rb
class Business::BillingsController < Business::BusinessApplicationController
  def index
    @billings = Promotion.order("id desc").page(params[:page]).per(10)
  end

  def show
    @billing = Promotion.find_by(id: params[:id])
  end
end

app/controllers/business/business_application_controller.rb
class Business::BusinessApplicationController < ApplicationController
  layout 'dashboard'

  before_action :get_analytics

  def get_analytics
    @get_analytics = Promotion.order("id desc").limit(5)
  end
end

app/controllers/business/home_controller.rb
class Business::HomeController < Business::BusinessApplicationController
  def dashboard
    
  end
end

app/controllers/business/promotions_controller.rb
class Business::PromotionsController < Business::BusinessApplicationController
  before_action :resource, only: [:edit, :update, :destroy, :show]

  def index
    @promotions = Promotion.order("id desc").page(params[:page]).per(10)
  end

  def show
    @promo = Promotion.find(params[:id])
    @visit = @promo.visitor_snapshot
    @visit_count = @visit.visitor_per_year.group_by_day(:created_at, format: "%d/%m/%y").count
    
    # count shares
    shares = @promo.buzzer_shares
    @shares = shares

    # count all share buzzer profile
    @get_buzzers = BuzzerProfile.where(buzzer_id: @shares.pluck(:buzzer_id))

    if @get_buzzers.present?
      # count by age
      @max_years = Time.now.year - @get_buzzers.where.not(born: nil).pluck(:born).min.year
      @min_years = Time.now.year - @get_buzzers.where.not(born: nil).pluck(:born).max.year

      # count by gender
      @gender = @get_buzzers.group(:gender).count

      # count share facebook
      @fb_shares = shares.where(provider: 'facebook')
      @fb_range_share = Buzzer.where(id: @fb_shares.pluck(:buzzer_id)).sum(:facebook_friends_count)

      # count share twitter
      @tw_shares = shares.where(provider: 'twitter')
      @tw_range_share = Buzzer.where(id: @tw_shares.pluck(:buzzer_id)).sum(:twitter_followers_count)

      # count share map location
      get_addresses_by_user = Address.where(user_id: shares.pluck(:buzzer_id).uniq)
      @province_locations = get_addresses_by_user.group(:province).count
      @locations = get_addresses_by_user.pluck(:city).uniq
    end
  end

  def new
    @promo = Promotion.new
  end

  def create
    @promo = Promotion.new(params_promotions)
    prepare_user
    prepare_min_max_age
    prepare_pricing
    if @promo.save
      VisitorSnapshot.create(visitorable_type: @promo.class.name, visitorable_id: @promo.id.to_s)
      redirect_to business_promotions_path
    else
      redirect_to business_promotions_path
    end
  end

  def edit
  end

  def update
    prepare_user
    prepare_min_max_age
    prepare_filter_blank(params)
    if @promo.update(params_promotions)
      redirect_to business_promotions_path
    else
      redirect_to business_promotions_path
    end
  end

  def destroy
    if @promo.destroy
      redirect_to business_promotions_path
    else
      redirect_to business_promotions_path
    end 
  end

  private
    def resource
      @promo = Promotion.find params[:id]
    end

    def params_promotions
      params.require(:promotion).permit(
                                        :title, 
                                        :cover, 
                                        :description,
                                        :content, 
                                        :quota, 
                                        :start_date, 
                                        :expired_date, 
                                        :range_age, 
                                        :min_age, 
                                        :max_age, 
                                        :gender, 
                                        :created_at, 
                                        :updated_at,
                                        :address,
                                        :longitude,
                                        :latitude,
                                        :url_facebook,
                                        :url_twitter,
                                        :url_instagram,
                                        :phone,
                                        url: [], mention: [], hashtag: [], cities: [], industries: [], providers: []
                                      )
    end

    def prepare_filter_blank(params)
      @promo.url = params[:promotion][:url].reject(&:empty?)
      @promo.hashtag = params[:promotion][:hashtag].reject(&:empty?)
      @promo.mention = params[:promotion][:mention].reject(&:empty?)
      @promo.cities = params[:promotion][:cities].reject(&:empty?)
      @promo.industries = params[:promotion][:industries].reject(&:empty?)
      @promo.providers = params[:promotion][:providers].reject(&:empty?)
    end

    def prepare_user
      @promo.user_id = current_user.id
    end

    def prepare_pricing
      @promo.price = 200 * params[:promotion][:quota].to_i
      @promo.fee = @promo.price * 40/100
      @promo.total = @promo.price + @promo.fee
    end

    def prepare_min_max_age
      @promo.min_age = @promo.range_age.split(',')[0]
      @promo.max_age = @promo.range_age.split(',')[1]
    end
end

app/controllers/domains/promotions/queries/by_tags.rb
module Promotion
  module Queries
    class ByTags
      def self.run(context_name)
        tags = ActsAsTaggableOn::Tagging.includes(:tag).where(context: context_name).distinct

        return tags
      end
    end
  end
end

app/views/business/promotions/_analytic.html.haml
/############ Analytics header ###############
.row
  .col-lg-12.text-center.m-t-md
    %h2
      Dashboard Data Buzzers <br>#{@promo.title}
    %p
      Di <b>Halaman Analytics</b> ini menunjukan segala data Buzzers yang anda sewa untuk menyebarkan iklan/promosi anda!
    %br
    %br

/############ All shares campaigns buzzers by facebook and twitter ###############
.row
  - if @promo.is_facebook_only?
    %div{class: @promo.is_facebook_only? && @promo.is_twitter_only? ? 'col-md-6' : 'col-md-12'}
      .hpanel.hbgblueold
        .panel-body
          .text-center
            %h3 Share di Facebook
            %p.text-big.font-light
              = @fb_shares.size rescue 0
            %small
              Potensi Jangkauan <br> Menjangkau #{@fb_range_share} orang

  - if @promo.is_twitter_only?
    %div{class: @promo.is_facebook_only? && @promo.is_twitter_only? ? 'col-md-6' : 'col-md-12'}
      .hpanel.hbgblue
        .panel-body
          .text-center
            %h3 Share di Twitter
            %p.text-big.font-light
              = @tw_shares.size rescue 0
            %small
              Potensi Jangkauan <br> Menjangkau #{@tw_range_share} orang
  / .col-md-3
  /   .hpanel.hbgnavyblue
  /     .panel-body
  /       .text-center
  /         %h3 Instagram
  /         %p.text-big.font-light
  /           750
  /         %small
  /           Potensi Jangkauan <br> Menjangkau 10.000 orang
  / .col-md-3
  /   .hpanel.hbgred
  /     .panel-body
  /       .text-center
  /         %h3 Youtube
  /         %p.text-big.font-light
  /           43
  /         %small
  /           Potensi Jangkauan <br> Menjangkau 10.000 orang

/############ All shares campaigns buzzers by grafic ###############
.row
  .col-lg-12
    .hpanel
      .panel-heading
        .panel-tools
          %a.showhide
            %i.fa.fa-chevron-up
          %a.closebox
            %i.fa.fa-times
        Biaya dan Kuota Buzzers
      .panel-body
        .row
          .col-md-3.text-center
            %br
            %i.pe-7s-cash.fa-4x
            %h1.m-xs.text-success
              = get_currency(@promo.price)
            %small Balance Promosi/Iklan
            %hr
            .row
              .col-xs-6
                %small.stats-label Terpakai
                %h4 #{get_currency(@promo.buzzer_shares.successed.sum(:reward))} <br><i class="fa fa-level-up text-danger"></i>
              .col-xs-6
                %small.stats-label Tersisa
                %h4 #{get_currency(@promo.budget?)} <br><i class="fa fa-plus text-success"></i>
            %hr
            .row
              .col-xs-12
                %small.stats-label Aktif Durasi Promosi/Iklan
                %h4 <i class="fa fa-clock-o"></i> #{@promo.duration?}

          .col-md-6
            .hpanel
              .panel-heading
                .panel-tools
                  %a.showhide
                    %i.fa.fa-chevron-up
                  %a.closebox
                    %i.fa.fa-times
                Dilihat Halaman Promosi/Iklan
              .panel-body
                %div
                  %canvas#lineOptions{:height => "140"}

          .col-md-3.text-center
            %br
            %i.pe-7s-share.fa-4x
            %h1.m-xs.text-success
              = @promo.quota
            %small Kuota Buzzers
            %hr
            .row
              .col-xs-6
                %h4 #{@promo.buzzer_shares.successed.size} <i class="fa fa-level-up text-danger"></i>
                %small.stats-label Terpakai
              .col-xs-6
                %h4 #{@promo.quota?} <i class="fa fa-plus text-success"></i>
                %small.stats-label Tersisa
              .col-xs-12
                %hr
              .col-xs-6
                %h4 #{@promo.buzzer_shares.rejected.size} <i class="fa fa-times text-danger"></i>
                %small.stats-label Gagal
              .col-xs-6
                %h4 #{@promo.buzzer_shares.only_successed.size} <i class="fa fa-check-circle-o text-success"></i>
                %small.stats-label Sukses
         
/############ All shares campaigns buzzers count ############### 
.row
  .col-lg-3
    .hpanel
      .panel-body
        .stats-title.pull-left
          %h4 Pengunjung
        .stats-icon.pull-right
          %i.pe-7s-display1.fa-4x
        .m-t-xl
          %h1.text-success #{@visit.impressionist_count(filter: :ip_address)} 
          %small Total Pengunjung
          %hr.hr12
          %small
            Data ini di dapatkan dari jumlah orang yang mengunjungi halaman promosi/iklan anda

  .col-lg-3
    .hpanel
      .panel-body
        .stats-title.pull-left
          %h4 Dilihat
        .stats-icon.pull-right
          %i.fa.fa-eye.fa-4x
        .m-t-xl
          %h1.text-success #{@visit.impressionist_count} 
          %small Telah Dilihat
          %hr.hr12
          %small
            Data ini di dapatkan dari berapa kali orang yang melihat halaman promosi/iklan anda

  .col-lg-3
    .hpanel.stats
      .panel-body.h-200
        .stats-title.pull-left
          %h4 Jenis Kelamin
          %br
        .stats-icon.pull-right
          %i.pe-7s-shuffle.fa-4x
        .clearfix
        .flot-chart
          #flot-pie-chart.flot-chart-content{:style => "height: 112px"}

  .col-lg-3
    .hpanel.stats
      .panel-body.h-200
        .stats-title.pull-left
          %h4 Jarak Umur
        .stats-icon.pull-right
          %i.pe-7s-users.fa-4x
        .m-t-xl
          %h1.text-success 
            = @get_buzzers.size
            %small Buzzers
          %hr
          .row
            .col-xs-6
              %small.stats-label Terendah
              %h4 #{@min_years rescue 0} Tahun
            .col-xs-6
              %small.stats-label Tertinggi
              %h4 #{@max_years rescue 0} Tahun

/############ All shares campaigns buzzers by table ###############
.row
  .col-lg-12
    .hpanel
      .panel-heading
        .panel-tools
          %a.showhide
            %i.fa.fa-chevron-up
          %a.closebox
            %i.fa.fa-times
        List Share Buzzers
      .panel-body.list
        - if @shares.present?
          .table-responsive.project-list
            %table.table.table-striped
              %thead
                %tr
                  %th.text-center No.
                  %th.text-center Buzzer
                  %th.text-center Via
                  %th.text-center Post Id
                  %th.text-center Engagement
                  %th.text-center Comment
                  %th.text-center Share
                  %th.text-center Kota
                  %th.text-center Waktu
                  %th.text-center Status
              %tbody
                - @shares.each_with_index do |f, index|
                  - usr = f.buzzer
                  %tr
                    %td.text-center
                      = index+1
                    %td.text-center
                      - if f.provider == 'facebook'
                        .img-circle.thumb-small{ src: usr.avatar.url(:thumb), 'data-toggle'=>"popover", 'data-trigger'=>'hover', 'data-placement'=>"top", 'data-html'=>"true", 'title'=>"<b>#{usr.username}</b> <br> <small style='font-weight:none;'>ID #{usr.facebook_uid} <br> #{usr.buzzer_profile.age} tahun</small>",'data-content'=>"<i class='fa fa-facebook-official' aria-hidden='true'></i>  <small>#{usr.facebook_friends_count} Friends</small>"}
                          = image_tag usr.avatar.url(:thumb)
                      - elsif f.provider == 'twitter'
                        .img-circle.thumb-small{ src: usr.avatar.url(:thumb), 'data-toggle'=>"popover", 'data-trigger'=>'hover', 'data-placement'=>"top", 'data-html'=>"true", 'title'=>"<b>#{usr.username}</b> <br> <small style='font-weight:none;'>ID #{usr.twitter_uid} <br> #{usr.buzzer_profile.age} tahun</small>",'data-content'=>"<i class='fa fa-twitter' aria-hidden='true'></i> <small>#{usr.twitter_followers_count} Followers</small>"}
                          = image_tag usr.avatar.url(:thumb)
                      = link_to usr.username,'#', class: 'label label-primary'
                    %td.text-center
                      <i class="fa fa-#{f.provider}"></i>
                    %td.text-center
                      = f.post_id
                    %td.text-center
                      = f.count_engagement?
                    %td.text-center
                      = f.count_comment?
                    %td.text-center
                      = f.count_share?
                    %td.text-center
                      = usr.try(:address).try(:city)
                    %td.text-center
                      = time_to_ago(f.created_at)
                    %td.text-center
                      = f.status?
        - else
          Tidak ada data yang ditemukan!
/############ All shares campaigns buzzers by map ###############
.row
  .col-lg-12
    .hpanel
      .panel-heading
        .panel-tools
          %a.showhide
            %i.fa.fa-chevron-up
          %a.closebox
            %i.fa.fa-times
        Lokasi Buzzers di Indonesia
      .panel-body
        .row
          .col-md-12
            #map_canvas_geochart{style: 'style="width: 90%; height: 20%;"'}


/############ All shares campaigns buzzers ###############
/ - if @shares.present?
/   .row
/     .col-lg-12
/       .hpanel
/         .panel-body
/           %b Hasil Penyebaran Campaigns

/     - @shares.each_with_index do |resource, index|
/       .col-md-4
/         - user = resource.buzzer
/         - promo = resource.promotion
/         .hpanel.item.blog-box
/           .panel-heading
/             .media.clearfix
/               %a.pull-left
/                 = image_tag user.avatar.url(:thumb)
/               .media-body
/                 %small
/                   %span.font-bold #{user.username.titleize}
/                   membagikan promosi anda <br>via <i class="fa fa-#{resource.provider}"></i> dengan post id <b>#{resource.post_id}</b>
/                 %br
/                 %small.text-muted 
/                   <i class="fa fa-clock-o"></i> #{time_to_ago(resource.created_at)}

/           = link_to buzzer_job_show_path(promo) do
/             .panel-image
/               .reward
/                 = resource.status?
/               = image_tag promo.cover.url(:normal)
/               .title
/                 %h4 
/                   = promo.title
/                 %small
/                   = promo.url.join('')
/           / .panel-body
/           /   %b #{promo.hashtag.join(' ')}
/           /   %br
/           /   %b #{promo.mention.join(' ')}
/           /   %br
/           /   %p #{promo.content}
/           /   - promo.industries.each do |i| 
/           /     <span class="label label-primary">#{i}</span>
/           .panel-footer
/             %span.pull-right
/               %i.fa.fa-comment-o
/               #{resource.count_comment} Comments
/             %i.fa.fa-thumbs-o-up
/             #{resource.count_engagement} Likes

app/views/business/promotions/edit.html.haml
.row{'ng-app' => "", 'ng-init' => "yourTitlePromo = '#{@promo.title}' ; yourContentPromo = '#{@promo.content}' ; yourUrlPromo = #{@promo.url.reject(&:empty?)} ; yourHashtagPromo = #{@promo.hashtag.reject(&:empty?)} ; yourMentionPromo = #{@promo.mention.reject(&:empty?)} ; yourIndustriPromo = #{@promo.industries.reject(&:empty?)} ; yourLocationPromo = #{@promo.cities.reject(&:empty?)} ; yourStartPromo = '#{@promo.start_date}' ; yourEndPromo = '#{@promo.expired_date}' ; yourGenderPromo = '#{@promo.gender}' ; yourBuzzersPromo = '#{@promo.quota}' ; yourAgePromo = '#{@promo.range_age}' ; yourProvidersPromo = #{@promo.providers.reject(&:empty?)} "}
  = form_for @promo, url: business_promotion_path(@promo), method: 'put' do |f|
    = render 'form', f: f

app/views/business/promotions/index.html.haml
%h1{align: 'center'} Promosi Iklan
%br
.row
  - if @promotions.present?
    - @promotions.each do |p|
      .col-lg-12.hpanel-bos-promo
        .hpanel.hgreen
          .panel-body
            .btn-group.pull-right
              = link_to '<i class="fa fa-wrench" aria-hidden="true"></i> Edit'.html_safe, edit_business_promotion_path(p), class: 'btn btn-xs btn-default'
              = link_to '<i class="fa fa-eye" aria-hidden="true"></i> View'.html_safe, business_promotion_path(p), class: 'btn btn-xs btn-default'
              / = link_to 'Delete', business_promotion_path(p), method: 'delete', data: {confirm: 'Are You Sure?'}, class: 'btn btn-xs btn-default'
            .row
              .col-sm-2
                .cover-image
                  = image_tag p.cover.url(:thumb)
              .col-sm-6
                %h4
                  = link_to "<i class='fa fa-flag-o'></i> #{p.title}".html_safe , ''
                %small 
                  #{p.status?} &nbsp;&nbsp; Kode: #{'#' + p.code} &nbsp;&nbsp; <i class="fa fa-clock-o"></i> #{time_to_ago(p.created_at)}
                %hr
                .row
                  .col-sm-3
                    .project-label <i class='pe-7s-like'></i> INDUSTRI
                    %small 
                      = p.industries.reject(&:empty?).join(', ')
                  .col-sm-3
                    .project-label <i class='pe-7s-map-marker'></i> KOTA
                    %small 
                      = p.cities.reject(&:empty?).join(', ')
                  .col-sm-3
                    .project-label <i class='pe-7s-graph1'></i> UMUR
                    %small #{p.min_age} - #{p.max_age} Thn
                  .col-sm-3
                    .project-label <i class='pe-7s-users'></i> JENIS KELAMIN
                    %small
                      = p.gender
              .col-sm-4.project-info
                .row.text-center
                  .col-xs-6
                    .project-value
                      %br
                      %h2.text-success
                        = get_currency(p.budget?)
                    .project-label SISA NOMINAL PROMOSI
                  .col-xs-6
                    .project-value
                      %br
                      %h2.text-success
                        = get_nominal(p.quota?)
                    .project-label SISA KUOTA BUZZERS

          .panel-footer
            <i class='pe-7s-alarm'></i> Masa Promosi : #{p.duration?}

    .col-lg-12
      = paginate @promotions
  - else
    .col-lg-12
      .panel
        .panel-body Tidak ada data yang ditemukan!

app/views/business/promotions/new.html.haml
- @package = params[:package].present? ? get_package_buzzers_value(params[:package]) : 500
.row{'ng-app' => "", 'ng-init' => "yourTitlePromo = 'Judul Promosi' ; yourContentPromo = '' ; yourUrlPromo = ['www.your-url.com/page'] ; yourHashtagPromo = ['#BrandCompanyHashtag'] ; yourMentionPromo = ['@myFriendName'] ; yourIndustriPromo = ['Semua Industri']; yourLocationPromo = ['Semua Kota'] ; yourStartPromo = '#{Time.zone.now.to_date}' ; yourEndPromo = '#{Time.zone.now.to_date}' ; yourGenderPromo = 'Semua Jenis Kelamin' ; yourBuzzersPromo = '#{@package}' ; yourAgePromo = '17 - 50' ; yourProvidersPromo = ['Facebook', 'Twitter']"}
  = form_for @promo, url: business_promotions_path, method: 'post' do |f|
    = render 'form', f: f

app/views/business/promotions/show.html.haml
= render 'business/promotions/analytic'